import { Resource, VisibilityMode, PermissionLevel, PermissionMember, ApprovalRequest, AuditLog } from './types';

export const mockResources: Resource[] = [
  {
    id: '1',
    name: '客服智能体 Alpha',
    type: '智能体',
    description: '高性能电商垂直场景客服助手',
    owner: '张三',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.OWNER,
    createdAt: '2024-03-20',
  },
  {
    id: '2',
    name: 'GPT-4 Turbo',
    type: '模型',
    description: '通用的高质量语言模型资源，具备极强的代码生成与逻辑推理能力。',
    owner: '系统管理员',
    visibilityMode: VisibilityMode.FULLY_PUBLIC,
    userPermission: PermissionLevel.USE,
    createdAt: '2024-03-15',
    modelType: '大模型',
    deploymentMode: '公网',
  },
  {
    id: '3',
    name: '财务数据回传接口',
    type: '自定义API',
    description: '用于同步季度财报的加密接口',
    owner: '李四',
    visibilityMode: VisibilityMode.FULLY_AUTHORIZED,
    userPermission: PermissionLevel.VISIBLE,
    createdAt: '2024-03-25',
  },
  {
    id: '4',
    name: '代码审核工作流',
    type: '工作流',
    description: '自动化代码规范检查与安全扫描',
    owner: '王五',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.USE,
    createdAt: '2024-03-22',
  },
  {
    id: '5',
    name: 'DALL-E 3',
    type: '模型',
    description: '先进的图像生成模型，支持高精度的文本到图像转换。',
    owner: 'OpenAI',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.VISIBLE,
    createdAt: '2024-04-01',
    modelType: '大模型',
    deploymentMode: '公网',
  },
  {
    id: '6',
    name: '全量客户画像数据源',
    type: '数据源',
    description: '覆盖全业务线客户标签、消费行为与偏好数据的核心数据仓库。',
    owner: '大数据部',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.VISIBLE,
    createdAt: '2024-04-10',
    databaseType: 'MySQL',
  },
  {
    id: '7',
    name: 'LangChain MCP',
    description: '标准模型上下文协议实现，支持快速集成第三方插件。',
    type: 'MCP',
    owner: '架构组',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.VISIBLE,
    createdAt: '2024-04-15',
  },
  {
    id: '8',
    name: '企业规章制度知识库',
    type: '知识库',
    description: '包含公司最新人事、财务、考勤等各项规章制度文档。',
    owner: '人力资源部',
    visibilityMode: VisibilityMode.PUBLIC_VISIBLE,
    userPermission: PermissionLevel.VISIBLE,
    createdAt: '2024-04-20',
    knowledgeBaseType: '文档知识库',
  },
];

export const mockMembers: PermissionMember[] = [
  { id: 'm1', name: '张三', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix', role: '所有权人', department: '总裁办', level: PermissionLevel.OWNER },
  { id: 'm2', name: '李四', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka', role: '系统工程师', department: '系统架构部', level: PermissionLevel.MANAGE },
  { id: 'm3', name: '赵六', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=George', role: '数据分析师', department: '运营推广部', level: PermissionLevel.USE, expiryDate: '2025-12-31' },
];

export const mockApprovals: ApprovalRequest[] = [
  {
    id: 'a1',
    userName: '钱七',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
    resourceName: '客服智能体 Alpha',
    reason: '需要调用该智能体进行售后自动回复测试',
    status: '待处理',
    submitTime: '2024-04-28 10:30',
  },
  {
    id: 'a2',
    userName: '周八',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucky',
    resourceName: '客服智能体 Alpha',
    reason: '申请用于双十一大促预热',
    status: '通过',
    submitTime: '2024-04-25 14:00',
    approvedLevel: PermissionLevel.USE,
    approvedExpiry: '永久有效'
  },
  {
    id: 'a3',
    userName: '吴九',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Cookie',
    resourceName: '客服智能体 Alpha',
    reason: '测试权限申请流程',
    status: '驳回',
    submitTime: '2024-04-20 09:15',
    rejectReason: '请提交正式申请，测试请求恕不处理。'
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'l15',
    operator: '李总（超级管理员）',
    action: '强制转移所有权',
    target: '郑十（个人）',
    detail: '将该资源所有权由 吴九（个人） 强制转移给：郑十（个人）。',
    time: '2026-05-12 17:00:00',
  },
  {
    id: 'l14',
    operator: '张三（所有权人）',
    action: '转移所有权',
    target: '吴九（个人）',
    detail: '将该资源所有权由 张三 转移给：吴九（个人），原所有权人权限变更为【管理权】。',
    time: '2026-05-12 16:00:00',
  },
  {
    id: 'l13',
    operator: '张三（所有权人）',
    action: '审批驳回',
    target: '周八（个人）',
    detail: '拒绝了 周八（个人） 的申请，驳回原因：“目前仅限内部调试”。',
    time: '2026-05-11 14:45:00',
  },
  {
    id: 'l12',
    operator: '张三（所有权人）',
    action: '审批通过',
    target: '孙七（个人）',
    detail: '同意了 孙七（个人） 的申请，系统已自动赋予其【使用权】。',
    time: '2026-05-11 14:30:00',
  },
  {
    id: 'l11',
    operator: '孙七（个人）',
    action: '提交使用申请',
    target: '资源申请',
    detail: '申请理由：“参与二季度营销活动，需要调用该接口测试”。',
    time: '2026-05-11 14:00:00',
  },
  {
    id: 'l10',
    operator: '张三（所有权人）',
    action: '批量移除授权',
    target: '刘一、陈二、张三、李四',
    detail: '移除了 刘一、陈二、张三、李四 的全部权限。',
    time: '2026-05-10 11:15:00',
  },
  {
    id: 'l9',
    operator: '王五（管理权人）',
    action: '批量修改有效期',
    target: '研发一部、研发二部',
    detail: '将 研发一部、研发二部 的有效期统一变更为 2026-10-01。',
    time: '2026-05-10 11:10:00',
  },
  {
    id: 'l8',
    operator: '张三（所有权人）',
    action: '批量变更权限级别',
    target: '多重对象',
    detail: '将 张三、李四、王五、前端组、测试组 的权限级别统一变更为【使用权】。',
    time: '2026-05-10 11:05:00',
  },
  {
    id: 'l7',
    operator: '张三（所有权人）',
    action: '批量添加授权',
    target: '多个对象',
    detail: '新增 3 个对象：前端组（部门）、李四（个人）、王五（个人）；分配级别：【使用权】，有效期至：2026-12-31。',
    time: '2026-05-10 11:00:00',
  },
  {
    id: 'l6',
    operator: '王五（管理权人）',
    action: '移除授权',
    target: '赵六（个人）',
    detail: '移除了 赵六（个人） 的全部权限。',
    time: '2026-05-10 10:45:00',
  },
  {
    id: 'l5',
    operator: '张三（所有权人）',
    action: '修改有效期',
    target: '产品经理（岗位）',
    detail: '将 产品经理（岗位） 的有效期由 2026-08-01 变更为【永久有效】。',
    time: '2026-05-10 10:30:00',
  },
  {
    id: 'l4',
    operator: '王五（管理权人）',
    action: '变更权限级别',
    target: '研发一部（部门）',
    detail: '将 研发一部（部门） 的权限级别由【仅可见】变更为【管理权】。',
    time: '2026-05-10 10:15:00',
  },
  {
    id: 'l3',
    operator: '张三（所有权人）',
    action: '添加授权',
    target: '李四（个人）',
    detail: '新增对象：李四（个人），分配级别：【使用权】，有效期至：2026-12-31。',
    time: '2026-05-10 10:00:00',
  },
  {
    id: 'l2',
    operator: '李总（超级管理员）',
    action: '强制修改全局模式',
    target: '全局策略',
    detail: '将全局权限模式由【完全授权】变更为【完全公开】。',
    time: '2026-05-10 09:15:00',
  },
  {
    id: 'l1',
    operator: '张三（所有权人）',
    action: '修改全局模式',
    target: '全局策略',
    detail: '将全局权限模式由【完全公开】变更为【公开可见，授权可用】。',
    time: '2026-05-10 09:00:00',
  },
];
